In [1]:
import warnings
warnings.filterwarnings('ignore')

# Pipeline

In [2]:
from transformers import pipeline

pipe = pipeline(
    task="text-classification",
    model='finiteautomata/beto-sentiment-analysis'
)

WARNING:tensorflow:From C:\Users\efclprd\anaconda3\envs\nlp2\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Device set to use cuda:0

In [3]:
pipe("esta receta es muy buena")

[{'label': 'POS', 'score': 0.9985853433609009}]

In [4]:
pipe("esta receta es mala")

[{'label': 'NEG', 'score': 0.9987868666648865}]

In [5]:
sentences = [
    "esta receta es muy mala",
    "esta receta es muy buena"
]

pipe(sentences)

[{'label': 'NEG', 'score': 0.9989500641822815},
 {'label': 'POS', 'score': 0.9985853433609009}]

In [6]:
pipe.__class__

transformers.pipelines.text_classification.TextClassificationPipeline

# Tasks

## Zero-shot-classification

In [7]:
pipe = pipeline("zero-shot-classification")

No model was supplied, defaulted to facebook/bart-large-mnli and revision d7645e1 (https://huggingface.co/facebook/bart-large-mnli).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cuda:0

In [8]:
pipe("This is a course about the transformers library",
     candidate_labels=["education", "politics", "business"])

{'sequence': 'This is a course about the transformers library',
 'labels': ['education', 'business', 'politics'],
 'scores': [0.9192399978637695, 0.06077896058559418, 0.019981082528829575]}

In [9]:
pipe.__class__

transformers.pipelines.zero_shot_classification.ZeroShotClassificationPipeline

## Text generation

In [10]:
pipe = pipeline("text-generation", model="distilgpt2")

Device set to use cuda:0

In [11]:
pipe(
    "In this course, we will learn how to",
    max_length=30,
    num_return_sequences=2
)

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

[{'generated_text': 'In this course, we will learn how to use it and what not to do with it. Each lesson will help you build a more effective approach to'},
 {'generated_text': "In this course, we will learn how to use it, as the data is limited. That's what I'm teaching today.\n\n\nIt"}]

## NER (name-entity-recognition)

In [12]:
pipe = pipeline("ner", grouped_entities=True)

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision 4c53496 (https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use cuda:0

In [13]:
pipe("My name is Eduardo and I work at the UCM in Madrid")

[{'entity_group': 'PER',
  'score': 0.99891305,
  'word': 'Eduardo',
  'start': 11,
  'end': 18},
 {'entity_group': 'ORG',
  'score': 0.9992889,
  'word': 'UCM',
  'start': 37,
  'end': 40},
 {'entity_group': 'LOC',
  'score': 0.9962613,
  'word': 'Madrid',
  'start': 44,
  'end': 50}]

## QA (question answering)

In [14]:
pipe = pipeline("question-answering")

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 564e9b5 (https://huggingface.co/distilbert/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cuda:0

In [15]:
pipe(
    question="where do I work?",
    context="My name is Eduardo and I work at UCM in Madrid"
)

{'score': 0.43633198738098145, 'start': 33, 'end': 36, 'answer': 'UCM'}

## Summarization

In [16]:
pipe = pipeline("summarization")

No model was supplied, defaulted to sshleifer/distilbart-cnn-12-6 and revision a4f8f3e (https://huggingface.co/sshleifer/distilbart-cnn-12-6).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cuda:0

In [17]:
pipe("""
Donald John Trump (born June 14, 1946) is an American politician, media personality, and businessman who is the 47th president of the United States. A member of the Republican Party, he served as the 45th president from 2017 to 2021.

Born into a wealthy New York City family, Trump graduated from the University of Pennsylvania in 1968 with a bachelor's degree in economics. He became the president of his family's real estate business in 1971, renamed it the Trump Organization, and began acquiring and building skyscrapers, hotels, casinos, and golf courses. He also launched side ventures, many licensing the Trump name, and filed for six business bankruptcies in the 1990s and 2000s. From 2004 to 2015, he hosted the reality television show The Apprentice, bolstering his fame as a billionaire. Presenting himself as a political outsider, Trump won the 2016 presidential election against Democratic Party nominee Hillary Clinton.

During his first presidency, Trump imposed a travel ban on seven Muslim-majority countries, expanded the Mexico–United States border wall, and enforced a family separation policy on the border. He rolled back environmental and business regulations, signed the Tax Cuts and Jobs Act, and appointed three Supreme Court justices. In foreign policy, Trump withdrew the U.S. from agreements on climate, trade, and Iran's nuclear program, and initiated a trade war with China. In response to the COVID-19 pandemic from 2020, he downplayed its severity, contradicted health officials, and signed the CARES Act. After losing the 2020 presidential election to Joe Biden, Trump attempted to overturn the result, culminating in the January 6 Capitol attack in 2021. He was impeached in 2019 for abuse of power and obstruction of Congress, and in 2021 for incitement of insurrection; the Senate acquitted him both times.

In 2023, Trump was found liable in civil cases for sexual abuse and defamation and for business fraud. He was found guilty in 34 counts of falsifying business records in 2024, making him the first U.S. president convicted of a felony. After winning the 2024 presidential election against then-vice president Kamala Harris, he was sentenced to a discharge, and two felony indictments against him for retention of classified documents and obstruction of the 2020 election were dismissed without prejudice.

Trump began his second presidency by pardoning around 1,500 January 6 rioters and initiating mass layoffs of federal workers. He imposed tariffs on nearly all countries at the highest level since the Great Depression and signed the One Big Beautiful Bill Act. His administration's actions—including the targeting of political opponents and civil society, the persecution of transgender people, the mass deportation of immigrants, and the extensive use of executive orders—have drawn over 300 lawsuits challenging their legality.

Since 2015, Trump's leadership style and political agenda—often referred to as Trumpism—have reshaped the Republican Party's identity. Many of his comments and actions have been characterized as racist or misogynistic. He has made many false or misleading statements during his campaigns and presidency, to a degree unprecedented in American politics. He promotes conspiracy theories. Trump's actions, especially in his second term, have been described as authoritarian and contributing to democratic backsliding. After his first term, scholars and historians ranked him as one of the worst presidents in American history.
""")

[{'summary_text': " Donald John Trump is the 47th president of the United States . He served as the 45th president from 2017 to 2021 . He was impeached in 2019 for abuse of power and obstruction of Congress, and in 2021 for incitement of insurrection . Trump's actions have been described as authoritarian and contributing to democratic backsliding ."}]

## Translation

In [18]:
pipe = pipeline("translation", model="Helsinki-NLP/opus-mt-en-es")

Device set to use cuda:0

In [19]:
pipe("My name is Eduardo and I work at UCM in Madrid")

[{'translation_text': 'Me llamo Eduardo y trabajo en la UCM de Madrid.'}]

# AutoTokenizer

In [20]:
from transformers import AutoTokenizer

model_id = "distilbert/distilbert-base-uncased-finetuned-sst-2-english"

tokenizer = AutoTokenizer.from_pretrained(model_id)

In [21]:
tokenizer.__class__

transformers.models.distilbert.tokenization_distilbert_fast.DistilBertTokenizerFast

In [22]:
tokenizer

DistilBertTokenizerFast(name_or_path='distilbert/distilbert-base-uncased-finetuned-sst-2-english', vocab_size=30522, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)

In [23]:
sentences = [
    "I've been waiting for a Huggingface course my whole life.",
    "I hate this so much!"
]

In [24]:
tokenized_sentences = tokenizer.tokenize(sentences)
tokenizer.convert_tokens_to_ids(tokenized_sentences)
ids = tokenizer.encode(sentences)
tokenizer.decode(ids)
tokenizer(sentences)

{'input_ids': [[101, 1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012, 102], [101, 1045, 5223, 2023, 2061, 2172, 999, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1]]}

In [25]:
inputs = tokenizer(sentences, padding=True, truncation=True, return_tensors='pt')
inputs

{'input_ids': tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102],
        [  101,  1045,  5223,  2023,  2061,  2172,   999,   102,     0,     0,
             0,     0,     0,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])}

# AutoModel

In [26]:
from transformers import AutoModel

model_id = 'distilbert/distilbert-base-uncased-finetuned-sst-2-english'
model = AutoModel.from_pretrained(model_id)

In [27]:
model.__class__

transformers.models.distilbert.modeling_distilbert.DistilBertModel

In [28]:
model

DistilBertModel(
  (embeddings): Embeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (transformer): Transformer(
    (layer): ModuleList(
      (0-5): 6 x TransformerBlock(
        (attention): DistilBertSdpaAttention(
          (dropout): Dropout(p=0.1, inplace=False)
          (q_lin): Linear(in_features=768, out_features=768, bias=True)
          (k_lin): Linear(in_features=768, out_features=768, bias=True)
          (v_lin): Linear(in_features=768, out_features=768, bias=True)
          (out_lin): Linear(in_features=768, out_features=768, bias=True)
        )
        (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        (ffn): FFN(
          (dropout): Dropout(p=0.1, inplace=False)
          (lin1): Linear(in_features=768, out_features=3072, bias=True)
          (lin2): Linear(in_features=3072, out_features=768, bias=True)
          (activation): GELUActivation()
        )
        (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      )
    )
  )
)

In [29]:
model.config

DistilBertConfig {
  "_attn_implementation_autoset": true,
  "activation": "gelu",
  "architectures": [
    "DistilBertForSequenceClassification"
  ],
  "attention_dropout": 0.1,
  "dim": 768,
  "dropout": 0.1,
  "finetuning_task": "sst-2",
  "hidden_dim": 3072,
  "id2label": {
    "0": "NEGATIVE",
    "1": "POSITIVE"
  },
  "initializer_range": 0.02,
  "label2id": {
    "NEGATIVE": 0,
    "POSITIVE": 1
  },
  "max_position_embeddings": 512,
  "model_type": "distilbert",
  "n_heads": 12,
  "n_layers": 6,
  "output_past": true,
  "pad_token_id": 0,
  "qa_dropout": 0.1,
  "seq_classif_dropout": 0.2,
  "sinusoidal_pos_embds": false,
  "tie_weights_": true,
  "torch_dtype": "float32",
  "transformers_version": "4.50.1",
  "vocab_size": 30522
}

# AutoConfig

In [30]:
from transformers import AutoConfig

model_id = 'distilbert/distilbert-base-uncased-finetuned-sst-2-english'
config = AutoConfig.from_pretrained(model_id)
model = AutoModel.from_config(config)

In [31]:
# config.dropout = 0.2

In [32]:
model.config

DistilBertConfig {
  "_attn_implementation_autoset": true,
  "activation": "gelu",
  "architectures": [
    "DistilBertForSequenceClassification"
  ],
  "attention_dropout": 0.1,
  "dim": 768,
  "dropout": 0.1,
  "finetuning_task": "sst-2",
  "hidden_dim": 3072,
  "id2label": {
    "0": "NEGATIVE",
    "1": "POSITIVE"
  },
  "initializer_range": 0.02,
  "label2id": {
    "NEGATIVE": 0,
    "POSITIVE": 1
  },
  "max_position_embeddings": 512,
  "model_type": "distilbert",
  "n_heads": 12,
  "n_layers": 6,
  "output_past": true,
  "pad_token_id": 0,
  "qa_dropout": 0.1,
  "seq_classif_dropout": 0.2,
  "sinusoidal_pos_embds": false,
  "tie_weights_": true,
  "transformers_version": "4.50.1",
  "vocab_size": 30522
}

In [33]:
outputs = model(**inputs)
last_hidden_state = outputs.last_hidden_state
last_hidden_state.shape

torch.Size([2, 16, 768])

In [34]:
import torch

with torch.no_grad():
    last_hidden_state = last_hidden_state.cpu().numpy()
    
last_hidden_state.shape

(2, 16, 768)

In [35]:
last_hidden_state[0][0].shape

(768,)

# Ejercicio (clasifición)

In [36]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/eduardofc/data/main/amazon_sports.csv")
df['review_body'] = df['review_body'].str.replace('[^a-zA-ZñÑáéíóú .,]', '', regex=True)
df['review_body'] = df['review_body'].str.lower()
df.head()

,stars,review_body,review_title,product_category
0,1,nunca llego el pedido y el vendedor pasa de to...,No llego nunca,sports
1,1,"no sé como es, porque debería haber llegado ay...",Todavía no ha llegado,sports
2,1,"guantes cómodos, no lo niego, pero de mala cal...",Guantes de baja calidad,sports
3,1,hasta hoy no he visto el producto. el pedido h...,Muy Mala experiencia,sports
4,1,"no puedo valorarla porque, después de casi una...",Paquete perdido?,sports

In [37]:
df = df[df.stars.isin([1,5])]
df['good_product'] = (df.stars>3).astype(int)
df.groupby('good_product').size()

good_product
0    2438
1    2512
dtype: int64

In [38]:
# 1) 
model_id = 'mrm8488/bert-base-spanish-wwm-cased-finetuned-spa-squad2-es'

# 2)
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModel.from_pretrained(model_id)

In [39]:
X = list(df.review_body.values)
y = df.good_product

In [40]:
X_inputs = tokenizer(X, padding=True, truncation=True, return_tensors='pt')
X_inputs

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

{'input_ids': tensor([[    4,  2185, 15961,  ...,     1,     1,     1],
        [    4,  1084,  1062,  ...,     1,     1,     1],
        [    4, 19531,  1184,  ...,     1,     1,     1],
        ...,
        [    4, 17906, 30935,  ...,     1,     1,     1],
        [    4,  7730, 12569,  ...,     1,     1,     1],
        [    4,  1620,  6784,  ...,     1,     1,     1]]), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])}

In [41]:
X_inputs.input_ids.shape

torch.Size([4950, 410])

In [42]:
# model(**X_inputs)

In [43]:
def forward_pass(x):
    inputs = tokenizer(x, padding=True, truncation=True, return_tensors='pt')
    outputs = model(**inputs)
    last_hidden_state = outputs.last_hidden_state
    with torch.no_grad():
        last_hidden_state = last_hidden_state.cpu().numpy()
    return last_hidden_state[0][0]

In [44]:
%%time

last_layer_model = df.review_body.map(forward_pass)

CPU times: total: 44min 31s
Wall time: 5min 37s

In [45]:
df_X = pd.DataFrame(last_layer_model.to_list(), columns=[f"feature_{ii}" for ii in range(768)])
df_X.head()

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_758,feature_759,feature_760,feature_761,feature_762,feature_763,feature_764,feature_765,feature_766,feature_767
0,-0.224101,0.217788,-0.268525,0.262171,0.589971,0.850098,0.343388,-0.417441,0.677684,0.284198,...,0.740481,-0.614095,0.218316,0.189897,0.749982,-0.077173,-0.121352,-0.026984,0.850956,-0.631194
1,-0.176770,-0.196464,0.101215,-0.316894,0.223993,0.962091,0.389885,-0.321996,1.074629,0.822023,...,-0.002832,-0.627515,0.221206,0.722416,1.038690,-0.297489,-0.529303,0.104827,0.546131,-0.586552
2,-0.272957,-0.542379,-0.151961,-0.040684,0.605506,0.648033,0.576040,-0.083504,0.564474,0.137163,...,1.173989,-0.447643,-0.010769,0.512982,1.122815,0.067183,0.003019,0.146406,0.230275,-0.867106
3,0.336199,-0.809659,-0.135591,-0.474448,0.257172,0.523675,0.517548,-0.278968,0.984238,0.487670,...,0.209875,-0.481032,-0.022264,0.463260,0.543832,-0.081682,-0.004623,0.020517,0.162385,-0.771167
4,-0.252668,0.105186,-0.278719,0.020189,-0.171582,0.753830,0.435040,-0.378253,0.778348,0.554699,...,1.006767,-0.430389,0.117657,0.452370,1.218982,0.004758,0.095248,0.007257,0.221123,-0.582683

In [46]:
from sklearn.model_selection import train_test_split

X = df_X
y = df.good_product

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=99)

In [47]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(random_state=99)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9353535353535354

# AutoModel for sequence classification

In [57]:
sentences

["I've been waiting for a Huggingface course my whole life.",
 'I hate this so much!']

In [58]:
from transformers import AutoModelForSequenceClassification

model_id = "distilbert-base-uncased-finetuned-sst-2-english"

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForSequenceClassification.from_pretrained(model_id)

In [59]:
model

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [61]:
inputs = tokenizer(sentences, padding=True, truncation=True, return_tensors='pt')
print(inputs)

{'input_ids': tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102],
        [  101,  1045,  5223,  2023,  2061,  2172,   999,   102,     0,     0,
             0,     0,     0,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])}

In [62]:
outputs = model(**inputs)
print(outputs)

SequenceClassifierOutput(loss=None, logits=tensor([[-1.5607,  1.6123],
        [ 4.1692, -3.3464]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [63]:
print(outputs.logits)

tensor([[-1.5607,  1.6123],
        [ 4.1692, -3.3464]], grad_fn=<AddmmBackward0>)

In [65]:
import torch

preds = torch.nn.functional.softmax(outputs.logits)
preds

tensor([[4.0195e-02, 9.5980e-01],
        [9.9946e-01, 5.4418e-04]], grad_fn=<SoftmaxBackward0>)

# All in a pipeline

In [67]:
sentences

["I've been waiting for a Huggingface course my whole life.",
 'I hate this so much!']

In [69]:
from transformers import DistilBertForSequenceClassification, DistilBertTokenizerFast

model_id = 'distilbert-base-uncased-finetuned-sst-2-english'

pipe = pipeline(
    task="text-classification",
    model=DistilBertForSequenceClassification.from_pretrained(model_id), 
    tokenizer=DistilBertTokenizerFast.from_pretrained(model_id, padding=True, truncation=True, return_tensors='pt'),
)

Device set to use cuda:0